--- #YAML:1.0
name:               chownfu
version:            1.05
abstract:           recursively chown user dirs to respective users and config file
author:
    - Leo Charre leocharre at cpan dot org
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Getopt::Std::Strict:  1.01
    LEOCHARRE::Dir:       1.07
    YAML:                 0.66
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
